server:
  port: 15006

spring:
  application:
    name: springboot-redis-demo
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 100

logging:
  level:
    root: INFO
    org.springframework.data.redis: INFO

